package cn.dingd.dd.biz.backgroud.dao;

import cn.dingd.dd.biz.common.entity.Auser;
import cn.dingd.dd.biz.common.entity.AuserExample;
import cn.dingd.dd.common.entity.CarDominantEntity;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface AuserMapper {

	 List<Map<String, Object>> selectFind(Auser auser);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_user
     *
     * @mbggenerated Wed Apr 25 16:55:27 CST 2018
     */
    int countByExample(AuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_user
     *
     * @mbggenerated Wed Apr 25 16:55:27 CST 2018
     */
    int deleteByExample(AuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_user
     *
     * @mbggenerated Wed Apr 25 16:55:27 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_user
     *
     * @mbggenerated Wed Apr 25 16:55:27 CST 2018
     */
    int insert(Auser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_user
     *
     * @mbggenerated Wed Apr 25 16:55:27 CST 2018
     */
    int insertSelective(Auser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_user
     *
     * @mbggenerated Wed Apr 25 16:55:27 CST 2018
     */
    List<Auser> selectByExample(AuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_user
     *
     * @mbggenerated Wed Apr 25 16:55:27 CST 2018
     */
    Auser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_user
     *
     * @mbggenerated Wed Apr 25 16:55:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") Auser record, @Param("example") AuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_user
     *
     * @mbggenerated Wed Apr 25 16:55:27 CST 2018
     */
    int updateByExample(@Param("record") Auser record, @Param("example") AuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_user
     *
     * @mbggenerated Wed Apr 25 16:55:27 CST 2018
     */
    int updateByPrimaryKeySelective(Auser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_user
     *
     * @mbggenerated Wed Apr 25 16:55:27 CST 2018
     */
    int updateByPrimaryKey(Auser record);
    
    List getAuserAddres(int id);
}